<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Identity core: users, their profile and their addresses.
 *
 * Conventions (08_DATABASE_AND_DOMAIN_RULES.md / 05_ARCHITECTURE_AND_CODE_RULES.md):
 *   - UUIDv7 primary keys, generated by the application
 *   - timestamps stored in UTC, displayed in the user's timezone
 *   - status values constrained in the database, not only in PHP
 *   - e-mail is citext so "Ali@x.com" and "ali@x.com" cannot both exist
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table): void {
            $table->uuid('id')->primary();

            $table->string('email')->nullable();
            $table->string('phone', 32)->nullable();
            $table->string('password_hash')->nullable();

            $table->string('status', 32)->default('pending_verification');
            $table->string('locale', 8)->default('tr');
            $table->string('timezone', 64)->default('Europe/Istanbul');

            $table->timestampTz('email_verified_at')->nullable();
            $table->timestampTz('phone_verified_at')->nullable();
            $table->timestampTz('last_login_at')->nullable();
            $table->string('last_login_ip', 45)->nullable();

            $table->timestampsTz();
            $table->softDeletesTz();

            $table->unique('email');
            $table->unique('phone');
            $table->index('status');
            $table->index('created_at');
        });

        // Case-insensitive e-mail: uniqueness must hold regardless of the casing a
        // customer types, otherwise duplicate accounts and login confusion follow.
        DB::statement('ALTER TABLE users ALTER COLUMN email TYPE citext');

        DB::statement(<<<'SQL'
            ALTER TABLE users
            ADD CONSTRAINT users_status_check
            CHECK (status IN ('pending_verification', 'active', 'suspended', 'banned'))
        SQL);

        // An account must be reachable by at least one channel; a row with neither is
        // unrecoverable and cannot be authenticated.
        DB::statement(<<<'SQL'
            ALTER TABLE users
            ADD CONSTRAINT users_contact_present_check
            CHECK (email IS NOT NULL OR phone IS NOT NULL)
        SQL);

        Schema::create('user_profiles', function (Blueprint $table): void {
            $table->uuid('user_id')->primary();
            $table->foreign('user_id')->references('id')->on('users')->cascadeOnDelete();

            $table->string('first_name', 120)->nullable();
            $table->string('last_name', 120)->nullable();
            $table->string('display_name', 160)->nullable();
            $table->string('avatar_path')->nullable();
            $table->date('birth_date')->nullable();
            $table->boolean('marketing_opt_in')->default(false);

            $table->timestampsTz();
        });

        Schema::create('user_addresses', function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->uuid('user_id');
            $table->foreign('user_id')->references('id')->on('users')->cascadeOnDelete();

            $table->string('label', 60)->nullable();
            $table->string('recipient_name', 160);
            $table->string('phone', 32)->nullable();

            $table->char('country_code', 2)->default('TR');
            $table->string('city', 120);
            $table->string('district', 120)->nullable();
            $table->string('neighbourhood', 160)->nullable();
            $table->string('address_line1', 255);
            $table->string('address_line2', 255)->nullable();
            $table->string('postal_code', 20)->nullable();

            $table->boolean('is_default_shipping')->default(false);
            $table->boolean('is_default_billing')->default(false);

            $table->timestampsTz();
            $table->softDeletesTz();

            $table->index(['user_id', 'deleted_at']);
        });

        // Exactly one default of each kind per user, enforced by partial unique indexes
        // so a concurrent update cannot produce two "default" shipping addresses.
        DB::statement(<<<'SQL'
            CREATE UNIQUE INDEX user_addresses_one_default_shipping
            ON user_addresses (user_id)
            WHERE is_default_shipping AND deleted_at IS NULL
        SQL);

        DB::statement(<<<'SQL'
            CREATE UNIQUE INDEX user_addresses_one_default_billing
            ON user_addresses (user_id)
            WHERE is_default_billing AND deleted_at IS NULL
        SQL);
    }

    public function down(): void
    {
        Schema::dropIfExists('user_addresses');
        Schema::dropIfExists('user_profiles');
        Schema::dropIfExists('users');
    }
};
